variables:
  dockerRegistryServiceConnection: 'saif-acr-connection'
  imageRepository: 'saif-app'
  containerRegistry: 'saifacr.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'